# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout treatments-xml
        uses: actions/checkout@v2
        with:
          path: xml
          fetch-depth: 2

      - name: Install saxon & rapper
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -y raptor2-utils openjdk-11-jdk
          curl -fsSL https://deno.land/x/install/install.sh | sudo DENO_INSTALL=/usr/local sh

      - name: Get changed XML files
        id: changed-xml-files
        uses: tj-actions/changed-files@v13.1
        with:
          path: xml

      - name: Run saxon on all modified files
        run: |
          cd $GITHUB_WORKSPACE/xml
          mkdir $GITHUB_WORKSPACE/rdf
          for file in ${{ steps.changed-xml-files.outputs.all_changed_files }}; do
            if [[ $file == *.xml ]]; then
              echo "$file is xml, applying saxon"
              mkdir -p $GITHUB_WORKSPACE/rdf/${file%/*}
              java -jar ./.github/workflows/saxon-he-10.8.jar -s:$file -o:$GITHUB_WORKSPACE/rdf/${file:0:-4}.rdf -xsl:gg2rdf.xslt
            fi
          done

      - name: Convert all generated RDF-XML files to TTL
        run: |
          cd $GITHUB_WORKSPACE/rdf
          mkdir -p $GITHUB_WORKSPACE/ttl
          for file in $(find . -type f); do
            echo "$file in generated rdf-xml folder"
            relative_file=`realpath -m --relative-to=$GITHUB_WORKSPACE/rdf $file`
            mkdir -p $GITHUB_WORKSPACE/ttl/${relative_file%/*}
            # $file → $GITHUB_WORKSPACE/ttl/${file:0:-4}.ttl
            rapper -w -q $file --output turtle > $GITHUB_WORKSPACE/ttl/${file:0:-4}.ttl
          done

      - name: Checkout treatments-rdf
        uses: actions/checkout@v2
        with:
          path: ttl-repo
          repository: plazi/treatments-rdf
          ref: main
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Apply Changes
        run: deno run -A $GITHUB_WORKSPACE/xml/.github/workflows/apply-changes.ts ${{ steps.changed-xml-files.outputs.deleted_files }}

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cd $GITHUB_WORKSPACE/ttl-repo
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git add -A
          git commit -m "committed by action runner ${{ github.repository }}@$GITHUB_SHA"
          git push origin main
